vacay <- read.csv("tourism_and_growth.csv", header = T, stringsAsFactors = F)
vacay <- vacay[, c(1, 2, 4, 11:15, 5:10)]


# making test/comparison group for housing outcomes
bad_cities <- c("Phoenix", "San Diego", "Miami", "San Francisco", "Las Vegas")
good_cities <- c("Atlanta", "Dallas", "Seattle", "New York", "Charlotte")

test_group <- vacay[vacay$city %in% c(bad_cities, good_cities),]

for (i in 1:nrow(test_group)){
	if (test_group$city[i] %in% bad_cities){
		test_group$outcome[i] <- "bad"
	} else test_group$outcome[i] <- "good"
}


# making graphs
library(ggplot2)
gdp_growth <- qplot(year, total, data = vacay[!is.na(vacay$state),], colour = city, facets  = ~ state, geom = "line", main = "Total GDP by city", ylab = "total GDP")
gdp_growth + opts(legend.position = "none")
ggsave("totalgdpbycity.pdf")


# there appears to be a significant amount of data entry error here. In particular, the units of measurement seem to differ between cities. So we'll just look at percentages.
vacay <- vacay[order(-vacay$total),]
vacay[1:100,]

gdp_shift <- qplot(year, real_estate/total*100, data = vacay[!is.na(vacay$state),], colour = city, facets  = ~ state, geom = "line", main = "Percent of GDP generated by real estate industries",ylab = "percent" )
gdp_shift + opts(legend.position = "none")
ggsave("realestategdpbycity.pdf")

tgdp_shift <- qplot(year, real_estate/total*100, data = test_group, colour = city, facets  =  ~ outcome, geom = "line", main = "Percent of GDP generated by real estate industries",ylab = "percent" )
tgdp_shift
# + opts(legend.position = "none")
ggsave("realestategdptest.pdf")

gdp_shift2 <- qplot(year, construction/total*100, data = vacay[!is.na(vacay$state),], colour = city, facets  =  ~ state, geom = "line", main = "Percent of GDP generated by construction industries",ylab = "percent" )
gdp_shift2 + opts(legend.position = "none")
ggsave("constructiongdpbycity.pdf")


tgdp_shift2 <- qplot(year, construction/total*100, data = test_group, colour = city, facets  =  ~ outcome, geom = "line", main = "Percent of GDP generated by construction industries",ylab = "percent" )
tgdp_shift2
# + opts(legend.position = "none")
ggsave("constructiongdptest.pdf")



# making vacation test group
vacation_locale <- c("Orlando", "Las Vegas", "Miami",  "Myrtle Beach", "Honolulu")
boring <- c("Scranton", "Ames", "Sacramento", "Worcester", "Amarillo")

test_group2 <- vacay[vacay$city %in% c(vacation_locale, boring),]


for (i in 1:nrow(test_group2)){
	if (test_group2$city[i] %in% vacation_locale){
		test_group2$vacation[i] <- "hot"
	} else test_group2$vacation[i] <- "not"
}

# making graphs

leisure_shift <- qplot(year, leisure/total*100, data = test_group2, colour = city, facets  = ~ vacation, geom = "line", main = "Percent of GDP generated by leisure and hospitality industries",ylab = "percent" )
leisure_shift 
# + opts(legend.position = "none")
ggsave("leisuregdpbytestgroup.pdf")

accomodations_shift <- qplot(year, accomodations/total*100, data = test_group2, colour = city, facets  = ~ vacation, geom = "line", main = "Percent of GDP generated by accomodation and food services  industries",ylab = "percent" )
accomodations_shift 
# + opts(legend.position = "none")
ggsave("accomodationsdpbytestgroup.pdf")

entertainment_shift <- qplot(year, entertainment/total*100, data = test_group2, colour = city, facets  = ~ vacation, geom = "line", main = "Percent of GDP generated by arts, entertainment, and recreation services  industries",ylab = "percent" )
entertainment_shift 
# + opts(legend.position = "none")
ggsave("entertainmentdpbytestgroup.pdf")

all_touristy_shift <- qplot(year, (accomodations + entertainment + leisure)/total*100, data = test_group2, colour = city, facets  = ~ vacation, geom = "line", main = "Percent of GDP generated by accomodation, entertainment, and leisure industries",ylab = "percent" )
all_touristy_shift 
# + opts(legend.position = "none")
ggsave("all_touristygdpbytestgroup.pdf")




